config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: [:edit, :update]
  
  root to: "rooms#index"

  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end

  resources :lists, only: [:new, :create]

  resources :groups, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord
  has_many :list_users
  has_many :users, through: :list_users

  validates :name, presence: true
end

app/models/list_user.rb
class ListUser < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :name, presence: true

  has_many :room_users
  has_many :rooms, through: :room_users

  has_many :messages

  has_many :list_users
  has_many :lists, through: :list_users

  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
 
  def new
    @group = Group.new
  end

  def create
  @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to root_path
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/new.html.erb
<div class='group-form'>
  <h1>新規グループ作成</h1>
  <%=form_with model: @group, local: true do |f|%>
    <div class='group-form__field'>
      <div class='group-form__field--left'>
        <%= f.label :グループ名, class: 'group-form__label'%>
      </div>
      <div class='group-form__field--right'>
        <%= f.text_field :name, class: 'group_name group-form__input', placeholder: 'グループ名を入力してください'%>
      </div>
    </div>
    <div class='group-form__field'>
    </div>
    <div class='group-form__field'>
      <div class='group-form__field--left'>
        <label class='group-form__label' for='group_グループメンバー'>グループメンバー</label>
      </div>
      <div class='group-form__field--right'>
        <%= 6.times do %>
          <select name="group[user_ids][]">
            <option value="">チャットするユーザーを選択してください</option>
            <% User.where.not(id: current_user.id).each do |user| %>
              <option value=<%= user.id %>><%= user.name %></option>
            <% end %>
          </select>
          <input name="group[user_ids][]" type="hidden" value=<%= current_user.id %>>
        <% end %>
      </div>
    </div>
    <div class='group-form__field'>
      <div class='group-form__field--left'></div>
      <div class='group-form__field--right'>
        <%= f.submit class: 'group-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OtsukaiApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/new.html.erb
<div class='list-form'>
  <h1>新規リスト</h1>
  <%=form_with model: @list, local: true do |l|%>
    <div class='list-form__field'>
      <div class='list-form__field--left'>
        <%= l.label :リスト名, class: 'list-form__label'%>
      </div>
      <div class='list-form__field--right'>
        <%= l.text_field :name, class: 'list_name list-form__input', placeholder: 'リスト名を入力してください'%>
      </div>
    </div>
    <div class='list-form__field'>
    </div>
    <div class='list-form__field'>
      <div class='list-form__field--left'>
        <label class='list-form__label' for='chat_room_リストメンバー'>リスト共有メンバー</label>
      </div>
      <div class='list-form__field--right'>
        <select name="list[user_ids][]">
          <option>リストを共有するユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id%>><%= user.name %></option>
          <% end %>
        </select>
        <input name="list[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='list-form__field'>
      <div class='list-form__field--left'></div>
      <div class='list-form__field--right'>
        <%= l.submit class: 'list-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to 'トップページへ戻る', root_path %>
    </div>
    <div class="header-button">
      <%= link_to '削除する', room_path(@room), method: :delete %>
    </div>
  </div>
</div>

<div class="messages">
  <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.content %>
    </div>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-content">
   <div class="header-name">
     <%= link_to current_user.name, edit_user_path(current_user) %>
    </div>
  </div>
</div>

<div class="side-content">
  <div class="groups">
    <div class="group-bar">
      <span class="side-title">グループ一覧</span>
      <div class="create-group">
        <%= link_to "グループ作成", new_group_path %>
      </div>
    </div>
    <% current_user.groups.each do |group| %>
      <div class="group">
        <div class="group-name">
          <span class="decoration">・</span>
          <div class="group-more">
            <a href="#"><%= group.name %></a>
            <div class="group-tag">
              <span class="decoration">[</span><%= link_to "削除", group_path(group.id), method: :delete %><span class="decoration">]</span>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="lists">
    <div class="list-bar">
      <span class="side-title">おつかいリスト</span>
      <div class="create-list">
        <%= link_to "リスト作成", new_list_path %>
      </div>
    </div>
    <% current_user.lists.each do |list| %>
      <div class="list">
        <div class="list-name">
          <span class="decoration">・</span><a href="#"><%= list.name %></a>
        </div>
      </div>
    <% end %>
  </div>

  <div class="rooms">
    <div class="room-bar">
      <span class="side-title">チャットルーム</span>
      <div class="create-room">
        <%= link_to "チャット作成", new_room_path %>
      </div>
    </div>
    <% current_user.rooms.each do |room| %>
      <div class="room">
        <div class="room-name">
          <span class="decoration">・</span><%= link_to room.name, room_messages_path(room) %></a>
       </div>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>